[build]
  command = "DISABLE_TTY=true remix env:replace TTY=false && remix init && remix vite:build"
  publish = "public"

[dev]
  command = "remix dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
